### PR TITLE
Mati test

### PR DESCRIPTION
**Pull request by mat-ilde**
Can you review my last commit, please?

### CODE REVIEW

**Comment by gsantam** [comment]
* Folder `hospitality-app-spring-` should be renamed to `hospitality-app-spring`
* That is the only folder in the commit and it seems to only contain a `HELP.md`. Could you check that you haven't missed to add anything to the commit?
* Could you provide some proof that the project is able to get deployed in Tomcat?

**Comment by mat-ilde** [comment]
v

**Comment by mat-ilde** [comment]
I have fixed the last PR. You can try the app displaying localhost:8080 and you will see a message, simple but prove that is working.

**Comment by mat-ilde** [comment]
https://drive.google.com/file/d/1iD4l2apO2Cd7CuUXQLkWHf3OWUpU5oSX/view?usp=sharing

The screenshot shows how the Tomcat server and spring boot are working displaying the text "Home".
To check this example, you need to go to **http://localhost:8080**/, which will automatically send you to a new page and will display the text.

**Review by gsantam — APPROVED** [review]
LGTM

**Pull request merged**
